apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops
  labels:
    env: devops
spec:
  storageClassName: jenkins-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi