apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels: 
    env: devops
spec:
  storageClassName: jenkins-storage
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /data/jenkins
    server: 192.168.50.200